# Generated by Django 4.2 on 2023-06-04 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_at',
            field=models.DateField(default=datetime.datetime(2025, 6, 3, 22, 57, 20, 397766)),
        ),
    ]
