# Generated by Django 4.2 on 2023-06-17 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_cart_user_alter_inventory_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_at',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 19, 5, 37, 322770)),
        ),
    ]
